---
title: 'finalproj'
author: "Jocelyn, Ana, Cat"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(lubridate) 
library(ggthemes)
library(ggdark)
```

```{r}
healthy_data <- read_csv("healthy_lifestyle_city_2021.csv", 
    col_types = cols(Rank = col_number(), 
        `Sunshine hours(City)` = col_number(), 
        `Cost of a bottle of water(City)` = col_number(), 
        `Obesity levels(Country)` = col_number(), 
        `Life expectancy(years) (Country)` = col_number(), 
        `Pollution(Index score) (City)` = col_number(), 
        `Annual avg. hours worked` = col_number(), 
        `Happiness levels(Country)` = col_number(), 
        `Outdoor activities(City)` = col_number(),
        `Number of take out places(City)` = col_number(), 
        `Cost of a monthly gym membership(City)` = col_number()))

# converting to dollars
healthy_data_dollars <- healthy_data %>% 
  mutate(water_bottle_cost = `Cost of a bottle of water(City)`*1.3,
         gym_cost = `Cost of a monthly gym membership(City)`*1.3)
```


```{r, r.height = 20, r.width = 15, fig.alt= "This dot plot compares the level of happiness to the sunshine hours in 43 different locations from the Healthy Lifestyle Cities Report 2021. The dots are all assigned a color based on location, and plotted at each discrete point. There appears to be no strong correlation between isolating the sunshine hours and comparing them to the happiness level. More factors combine to make up overall happiness."}
healthy_lifestyle_data_cat <- healthy_data_dollars[-c(20),]

healthy_lifestyle_data_cat %>% 
  select(`City`, `Happiness levels(Country)`, `Sunshine hours(City)`) %>% 
  
  ggplot(aes(x = `Happiness levels(Country)`, 
             y = factor(`Sunshine hours(City)`), 
             color = (`City`))) +
  geom_count() +
  scale_y_discrete(breaks = c(1405, 1884, 2363, 2983, 3542))+
  
  labs(title = "Is there a correlation between sunshine hours and happiness levels?",
       x = "Happiness Level",
       y = "Sunshine Hours",
       caption = "Graph By Cat Terres; data sourced from Kaggle, 
       'Healthy Lifestyle Cities Report 2021'") +
  
  theme_foundation() +
  theme(legend.title=element_blank())+
  theme(legend.background = element_blank())
       
  
  

```

Which cities are the sunniest and least sunny?
```{r, fig.alt = "Graph of the top 10 and bottom 10 cities by annual sunshine hours.The cities are mapped on the y-axis while the sunshine hours is mapped on the x-axis. Cairo, Tel Aviv, and Los Angeles were the top three trending just over 3000 annual sunshine hours while Brussels, Dublin, and Taipei were the bottom three with around 1500 annual sunshine hours."}
top_10 <- healthy_data_dollars %>% 
  arrange(desc(`Sunshine hours(City)`)) %>% 
  slice(1:10) %>% 
  ggplot(aes(y = fct_reorder(City,`Sunshine hours(City)`), x = `Sunshine hours(City)`)) +
  geom_col(fill = "khaki") +
  labs(title = "Top 10 and Bottom 10 Cities by Annual Sunshine Hours",
       y = "",
       x = "") +
  dark_theme_minimal()

bottom_10 <- healthy_data_dollars %>% 
  arrange(`Sunshine hours(City)`) %>% 
  slice(1:10) %>% 
  ggplot(aes(y = fct_reorder(City,`Sunshine hours(City)`), x = `Sunshine hours(City)`)) +
  geom_col(fill = "khaki") +
  xlim(0,3540) +
  labs(y = "",
       x = "",
       caption = "Data from UK Healthy Lifestyle Cities Report 2021, Graph by Jocelyn Radke") +
  dark_theme_minimal()

grid.arrange(top_10, bottom_10, nrow=2)
```


